server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      default-filters:
        - AddResponseHeader=X-Gateway, API-Gateway

      routes:
        - id: client-api
          uri: lb://client-api
          predicates:
            - Path=/api/v1/clients/**
          filters:
            - StripPrefix=2

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always