spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false

  cloud:
    discovery:
      enabled: true

clients:
  service:
    url: ${CLIENT_SERVICE_URL:}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
