version: "3.9"

services:
  postgres-customer:
    image: postgres:16
    container_name: postgres-customer
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
    ports:
      - "5433:5432"
    volumes:
      - customer_pgdata:/var/lib/postgresql/data

volumes:
  customer_pgdata:
